name: Publish

on:
  push:
    branches:
      - master

<<<<<<< HEAD
permissions:
=======
permissions: 
>>>>>>> bbec4378 (first)
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Composer
      run: composer install --no-progress --no-suggest

    - name: Node
      run: npm install
<<<<<<< HEAD

    - name: Production
      run: npm run prod

=======
      
    - name: Production
      run: npm run prod
      
>>>>>>> bbec4378 (first)
    - name: CNAME
      run: echo "privacyfed.github.io/doc_extrafield" > ./build_production/CNAME

    - name: gh-pages
      uses: JamesIves/github-pages-deploy-action@v4.4.2
      with:
        branch: gh-pages
        folder: build_production
