name: phpinsights
on: [push]

jobs:
    phpinsights:
        runs-on: ubuntu-latest
        name: PHP Insights checks
        steps:
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
            - uses: actions/checkout@v2
            - uses: shivammathur/setup-php@v2
=======
            - uses: actions/checkout@v4
            - uses: shivammathur/setup-php@latest
>>>>>>> d79d9e57 (first)
=======
            - uses: actions/checkout@v2
            - uses: shivammathur/setup-php@latest
>>>>>>> 0d55b583 (first)
=======
            - uses: actions/checkout@v2
            - uses: shivammathur/setup-php@latest
>>>>>>> 9cec72d6 (first)
=======
            - uses: actions/checkout@v2
            - uses: shivammathur/setup-php@latest
>>>>>>> 8fc3049b (first)
              with:
                  php-version: 8.1
            - run: composer install --prefer-dist --no-progress
            - run: composer require nunomaduro/phpinsights --dev
            - run: cp vendor/nunomaduro/phpinsights/stubs/laravel.php phpinsights.php
            - run: vendor/bin/phpinsights -n --ansi --format=github-action --fix
            - uses: stefanzweifel/git-auto-commit-action@latest
              with:
                commit_message: phpinsights
