name: PHPStan

on:
  push:
    paths:
      - '**.php'
      - 'phpstan.neon.dist'
<<<<<<< HEAD
  pull_request:
    paths:
      - '**.php'
      - 'phpstan.neon.dist'

=======
>>>>>>> a8f30311 (first)

jobs:
  phpstan:
    name: phpstan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
<<<<<<< HEAD
        uses: shivammathur/setup-php@v2
=======
        uses: shivammathur/setup-php@latest
>>>>>>> a8f30311 (first)
        with:
          php-version: '8.1'
          coverage: none

      - name: Install composer dependencies
<<<<<<< HEAD
<<<<<<< HEAD
        uses: ramsey/composer-install@v2
=======
        uses: ramsey/composer-install@latest

      - name: Install Services composer dependencies
        run: cd Services && composer install --no-progress --no-suggest
>>>>>>> 59bc4fe7 (first)

=======
        uses: ramsey/composer-install@latest

>>>>>>> a8f30311 (first)
      - name: Run PHPStan
        run: ./vendor/bin/phpstan --error-format=github
