name: Publish

on:
  push:
    branches:
      - master

<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
permissions: 
=======
permissions:
>>>>>>> 59bc4fe7 (first)
=======
permissions: 
>>>>>>> a8f30311 (first)
=======
permissions:
>>>>>>> bbec4378 (first)
=======
permissions:
>>>>>>> c088001a (first)
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Validate composer.json and composer.lock
      run: cd docs && composer validate

    - name: Composer
      run: cd docs && composer install --no-progress --no-suggest

    - name: Node
      run: cd docs && npm install
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
=======
>>>>>>> a8f30311 (first)
      
    - name: Production
      run: cd docs && npm run prod
      
    - name: CNAME
<<<<<<< HEAD
      run: cd docs && echo "laraxot.github.io/module_rating" > ./build_production/CNAME
=======
=======
>>>>>>> bbec4378 (first)
=======
>>>>>>> c088001a (first)

    - name: Production
      run: cd docs && npm run prod

    - name: CNAME
<<<<<<< HEAD
<<<<<<< HEAD
      run: cd docs && echo "laraxot.github.io/module_xot_fila3" > ./build_production/CNAME
>>>>>>> 59bc4fe7 (first)

=======
      run: cd docs && echo "laraxot.github.io/module_activity" > ./build_production/CNAME
    
>>>>>>> a8f30311 (first)
    - name: gh-pages
      uses: JamesIves/github-pages-deploy-action@latest
=======
      run: cd docs && echo "laraxot.github.io/module_lang" > ./build_production/CNAME

    - name: gh-pages
      uses: JamesIves/github-pages-deploy-action@v4.5
>>>>>>> bbec4378 (first)
=======
      run: cd docs && echo "laraxot.github.io/module_job" > ./build_production/CNAME

    - name: gh-pages
      uses: JamesIves/github-pages-deploy-action@latest
>>>>>>> c088001a (first)
      with:
        branch: gh-pages
        folder: ./docs/build_production
